#!/bin/bash

command=
key=

while [ $# -gt 0 ] 
do 
	case $1 in 
		a)	command=a; ;; 
		x)	command=x; ;;
		-k)	key=$2; shift ;; 
		-*)
            		echo >&2 "usage: $0 a|x -k keyfile ..."
	    		exit 1;;
		*)	break;;	# terminate while loop
	esac
	shift
done

echo command=$command
echo key=$key
encryptedPasswordFile=archivePassword.ssl

archiveCommand=/usr/bin/7z

case $command in
	a)
		input=*.txt
		output=test.7z

		archivePassword=`makepasswd --chars=30`
		echo "Archive password: $archivePassword"

		openssl rsautl -encrypt -inkey $key -pubin | $archiveCommand a $output -is$encryptedPasswordFile
		$archiveCommand u -p$archivePassword $output $input

		;;
	x)
		input=*.txt
		output=test.7z

		archivePassword=`$archiveCommand e $output $encryptedPasswordFile -so | openssl rsautl -decrypt -inkey $key -in $encryptedPasswordFile`
		echo "Archive password: $archivePassword"

		$archiveCommand x -p$archivePassword $output

		;;
esac

exit 0
