#!/bin/bash

set -x

archiveCommand=7z

key=
command=
options=
archive=test.7z
arguments=

while [ $# -gt 0 ] 
do 
	case $1 in 
		-k)	key=$2;
		    shift
		    ;;
		a) command=$1
			shift
			archive=$1
			shift
			arguments=$*
			break
			;;
		x) command=$1
			shift
			archive=$1
			shift
			arguments=$*
			break
			;;
		*) echo >&2 "usage: $0 -k keyfile a|x ..."
		    exit 1;;
	esac
	shift
done

echo key=$key
echo command=$command
echo options=$options
echo archive=$archive
echo arguments=$arguments

encryptedPasswordFile=archivePassword.ssl


case $command in
	a)
		archivePassword=`openssl rand -hex 32`
		echo "Archive password: $archivePassword"

		echo $archivePassword | \
			openssl rsautl -encrypt -inkey $key -pubin | \
			$archiveCommand $command $archive -si$encryptedPasswordFile

		$archiveCommand u $archive -p$archivePassword $arguments
		echo Done encrypting

		;;
	x)
		archivePassword=`$archiveCommand e -so $archive $encryptedPasswordFile | openssl rsautl -decrypt -inkey $key`
		echo "Archive password: $archivePassword"

		$archiveCommand $command $archive -p$archivePassword  $arguments -x!$encryptedPasswordFile
		echo Done decrypting
		;;
esac

exit 0
